ALL:
	g++ -c -std=c++0x SegmentTreeTDTest.cpp SegmentTreeMinTest.cpp \
        SuffixArrayTest.cpp CongruentIntTest.cpp AhoCorasickTest.cpp \
        DFSTest.cpp TopologicalSortTest.cpp BitmaskTest.cpp unittest.cpp
	g++ -o unittest *.o -l cppunit
